# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6f3074c32a7e00355b31a1045f8f00a870feb1aba61d62bad15ba697bfd18031d37e31f2064f97b5b576f58e50fee4ca7c7411bba6bc0bcf69f7ec6895e6ef

test:
  secret_key_base: 3ad6f8db640be519aa9f481dc4c366aac5d1ef41b4642e07481f5283de84a9fac86cd43cfa1254f7a172b9a98fb88b0473f2aff259482f56199e0786f52ddf5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
